spring.application.name=productInventory

spring.datasource.url=jdbc:mysql://localhost:3306/inventorycart
spring.datasource.username=root
spring.datasource.password=RonitDalal@272003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=MYSQL